//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_trunk
    {
        public string ant_trunk_id { get; set; }
        public string ant_trunk_code { get; set; }
        public string ant_trunk_title { get; set; }
        public string ant_trunk_entitle { get; set; }
        public string ant_trunk_summary { get; set; }
        public string ant_trunk_content { get; set; }
        public string ant_trunk_class_id { get; set; }
        public string ant_content_tags { get; set; }
        public Nullable<int> ant_trunk_stasus { get; set; }
        public Nullable<int> ant_trunk_order { get; set; }
        public Nullable<System.DateTime> ant_trunk_editdate { get; set; }
        public string ant_trunk_adduser { get; set; }
        public Nullable<System.DateTime> ant_trunk_adddate { get; set; }
        public string ant_trunk_edituser { get; set; }
        public string ant_trunk_area { get; set; }
    }
}
