//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_singlepage
    {
        public string ant_singlepage_id { get; set; }
        public string ant_singlepage_title { get; set; }
        public string ant_singlepage_content { get; set; }
        public string ant_singlepage_keywords { get; set; }
        public string ant_singlepage_description { get; set; }
        public string ant_singlepage_adduser { get; set; }
        public Nullable<System.DateTime> ant_singlepage_adddate { get; set; }
        public string ant_singlepage_edituser { get; set; }
        public Nullable<System.DateTime> ant_singlepage_editdate { get; set; }
        public string ant_singlepage_stasus { get; set; }
        public string ant_singlepage_class { get; set; }
    }
}
