//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_role
    {
        public string ant_role_id { get; set; }
        public string ant_role_name { get; set; }
        public string ant_role_purview { get; set; }
        public string ant_role_order { get; set; }
        public string ant_role_stastus { get; set; }
        public string ant_role_adduser { get; set; }
        public Nullable<System.DateTime> ant_role_adddate { get; set; }
        public string ant_role_edituser { get; set; }
        public Nullable<System.DateTime> ant_role_editdate { get; set; }
    }
}
