//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_trunk_content
    {
        public string ant_content_id { get; set; }
        public string ant_trunk_code { get; set; }
        public string ant_content_content { get; set; }
        public string ant_content_keywords { get; set; }
        public string ant_content_description { get; set; }
    }
}
