//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_class
    {
        public string ant_class_id { get; set; }
        public string ant_class_name { get; set; }
        public string ant_class_parent { get; set; }
        public string ant_class_attribute { get; set; }
        public Nullable<int> ant_class_stasus { get; set; }
        public string ant_class_adduser { get; set; }
        public Nullable<System.DateTime> ant_class_adddate { get; set; }
        public string ant_class_edituser { get; set; }
        public Nullable<System.DateTime> ant_class_editdate { get; set; }
    }
}
