//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_admin
    {
        public string ant_admin_id { get; set; }
        public int ant_admin_code { get; set; }
        public string ant_admin_name { get; set; }
        public string ant_admin_pwd { get; set; }
        public string ant_admin_role { get; set; }
        public string ant_admin_adduser { get; set; }
        public Nullable<System.DateTime> ant_admin_adddate { get; set; }
        public string ant_admin_edituser { get; set; }
        public Nullable<System.DateTime> ant_admin_editdate { get; set; }
    }
}
