//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_links
    {
        public string ant_links_id { get; set; }
        public string ant_links_name { get; set; }
        public string ant_links_url { get; set; }
        public string ant_links_orders { get; set; }
        public string ant_links_class { get; set; }
        public string ant_links_adduser { get; set; }
        public Nullable<System.DateTime> ant_links_adddate { get; set; }
        public string ant_links_edituser { get; set; }
        public Nullable<System.DateTime> ant_links_editdate { get; set; }
    }
}
