//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class ant_feedback
    {
        public string ant_feedback_id { get; set; }
        public string ant_feedback_code { get; set; }
        public string ant_feedback_title { get; set; }
        public string ant_feedback_content { get; set; }
        public string ant_feedback_name { get; set; }
        public string ant_feedback_mail { get; set; }
        public string ant_feedback_tel { get; set; }
        public string ant_feedback_qq { get; set; }
        public string ant_feedback_wechat { get; set; }
        public string ant_feedback_weibo { get; set; }
        public Nullable<System.DateTime> ant_feedback_adddate { get; set; }
    }
}
