//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class D8WeChatEntities : DbContext
    {
        public D8WeChatEntities()
            : base("name=D8WeChatEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ant_admin> ant_admin { get; set; }
        public DbSet<ant_class> ant_class { get; set; }
        public DbSet<ant_feedback> ant_feedback { get; set; }
        public DbSet<ant_img> ant_img { get; set; }
        public DbSet<ant_links> ant_links { get; set; }
        public DbSet<ant_purview> ant_purview { get; set; }
        public DbSet<ant_role> ant_role { get; set; }
        public DbSet<ant_singlepage> ant_singlepage { get; set; }
        public DbSet<ant_trunk_content> ant_trunk_content { get; set; }
        public DbSet<com_area> com_area { get; set; }
        public DbSet<com_img> com_img { get; set; }
        public DbSet<ant_trunk> ant_trunk { get; set; }
    }
}
